#!/bin/sh

set -e

base='docker.io/tpimenta/nginx-ldap-auth'
version='v1.0.2'
image="$base:$version"

atexit() {
	docker images -q -f dangling=true | xargs -r docker rmi
}

trap atexit INT TERM EXIT

docker build \
	--force-rm \
	--no-cache \
	--tag "$image" \
	"$(dirname "$0")"

docker push "$image"
docker tag "$image" "$base:latest"
docker push "$base:latest"
